path: C:/Users/ETRI/Desktop/PLD_project/data/AIHub  # modifiy to your path
train: images/train  # train images (relative to 'path')
val: images/test  # val images (relative to 'path') 
test:  # test images (optional)

# Classes
names:
  0: caf_traffic_light
  1: pedestrian_traffic_light